export default [
  {
    files: ["src/**/*.ts", "tests/**/*.ts"],
    ignores: ["node_modules/**", "dist/**", "*.d.ts"],
    rules: {
      "no-unused-vars": "error",
      "no-console": "warn",
      "prefer-const": "error",
      "no-var": "error",
      eqeqeq: ["error", "always"],
      curly: ["error", "all"],
      "brace-style": ["error", "1tbs"],
      semi: ["error", "always"],
      quotes: ["error", "single"],
      indent: ["error", 2],
      "comma-dangle": ["error", "always-multiline"],
      "no-trailing-spaces": "error",
      "eol-last": ["error", "always"],
      "max-len": ["warn", { code: 120 }],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-empty-function": ["warn", { allow: ["arrowFunctions", "functions", "methods"] }],
      "no-unreachable": "error",
      "no-constant-condition": "warn",
      "no-duplicate-imports": "error",
      "no-useless-catch": "error",
      "no-useless-return": "error",
      "prefer-template": "error",
      "prefer-arrow-callback": "error",
      "arrow-spacing": ["error", { before: true, after: true }],
      "template-curly-spacing": ["error", "never"],
      "object-curly-spacing": ["error", "always"],
      "array-bracket-spacing": ["error", "never"],
      "key-spacing": ["error", { beforeColon: false, afterColon: true }],
      "space-before-function-paren": [
        "error",
        { anonymous: "always", named: "never", asyncArrow: "always" },
      ],
      "space-before-blocks": "error",
      "space-infix-ops": "error",
      "spaced-comment": ["error", "always", { markers: ["/"] }],
    },
  },
];
